Repository Kusitms-29th-ASAP/Frontend, pull requests merged in 2024-05, with the labels that each got.

#7 [Feat] 공통 컴포넌트 제작
  .storybook/preview.ts
  next.config.mjs
  package.json
  public/assets/icons/ic_check_orange.svg
  public/assets/icons/ic_check_white.svg
  public/assets/icons/ic_class.svg
  public/assets/icons/ic_class_select.svg
  public/assets/icons/ic_edu.svg
  public/assets/icons/ic_edu_select.svg
  public/assets/icons/ic_home.svg
  public/assets/icons/ic_home_select.svg
  public/assets/icons/ic_mypage.svg
  public/assets/icons/ic_mypage_select.svg
  public/assets/icons/ic_store.svg
  public/assets/icons/ic_store_select.svg
  src/components/common/Button.tsx
  src/components/common/Checkbox.tsx
  src/components/common/Input.tsx
  src/components/common/Tabbar.tsx
  src/stories/Button.stories.ts
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Checkbox.stories.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Input.stories.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/Tabbar.stories.tsx
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/theme.ts
  yarn.lock
Labels: 🛠feat

#12 [Feat/#9] 홈 화면 UI
  custom.d.ts
  package.json
  public/assets/icons/ic_chevron_left.svg
  public/assets/icons/ic_chevron_right.svg
  public/assets/icons/ic_close.svg
  public/assets/icons/ic_close_white.svg
  public/assets/icons/ic_flip.svg
  public/assets/icons/ic_minus-circle.svg
  public/assets/icons/ic_plus.svg
  public/assets/images/home_egg.svg
  public/assets/index.ts
  src/app/global.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Button.tsx
  src/components/common/Card.tsx
  src/components/common/CustomInput.tsx
  src/components/common/ListBox.tsx
  src/components/common/ListNumber.tsx
  src/components/common/Popup.tsx
  src/components/common/Tabbar.tsx
  src/components/common/Toast.tsx
  src/components/home/AddTodoPopup.tsx
  src/components/home/HomePage.tsx
  src/components/home/Meal.tsx
  src/components/home/MealTable.tsx
  src/components/home/MealTablePopup.tsx
  src/components/home/Notification.tsx
  src/components/home/Ready.tsx
  src/components/home/TimeTable.tsx
  src/components/home/Todo.tsx
  src/data/homeData.ts
  src/stories/Input.stories.tsx
  src/styles/GlobalFont.ts
  src/styles/theme.ts
  yarn.lock
Labels: 🛠feat

#10 [Feat] 회원가입/로그인 UI
  public/assets/common/down_arrow.svg
  public/assets/common/garde2.svg
  public/assets/common/grade1.svg
  public/assets/common/grade3.svg
  public/assets/common/grade4.svg
  public/assets/common/grade5.svg
  public/assets/common/grade6.svg
  public/assets/common/left_arrow.svg
  public/assets/common/right_arrow.svg
  public/assets/main/complete_background.svg
  public/assets/main/kakao_social.svg
  public/assets/main/main_background.svg
  src/app/global.css
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/signin/completion/page.tsx
  src/app/signin/process1/page.tsx
  src/app/signin/process2/page.tsx
  src/app/signin/process3-1/page.tsx
  src/app/signin/process3/page.tsx
  src/app/signin/process4/page.tsx
  src/app/signin/terms/page.tsx
  src/components/common/Button.stories.tsx
  src/components/common/Button.tsx
  src/components/common/Checkbox.stories.tsx
  src/components/common/Checkbox.tsx
  src/components/common/CustomInput.tsx
  src/components/common/Input.stories.tsx
  src/components/common/Tabbar.stories.tsx
  src/components/common/Tobbar.stories.tsx
  src/components/common/Tobbar.tsx
  src/components/signin/ProgressBar.tsx
  src/components/signin/Subtitle.tsx
  src/context/Allergy.ts
  src/styles/GlobalFont.ts
Labels: 💄design

#17 [Design] 가정학습 메인 페이지
  .env
  public/assets/icons/ic_store.svg
  public/assets/icons/ic_store_select.svg
  public/assets/icons/ic_study.svg
  public/assets/icons/ic_study_select.svg
  public/assets/study/banner.svg
  public/assets/study/review1.svg
  public/assets/study/review2.svg
  public/assets/study/review3.svg
  public/assets/study/review4.svg
  public/assets/study/subject/study1.svg
  public/assets/study/subject/study10.svg
  public/assets/study/subject/study10_selected.svg
  public/assets/study/subject/study11.svg
  public/assets/study/subject/study11_selected.svg
  public/assets/study/subject/study1_selected.svg
  public/assets/study/subject/study2.svg
  public/assets/study/subject/study2_selected.svg
  public/assets/study/subject/study3.svg
  public/assets/study/subject/study3_selected.svg
  public/assets/study/subject/study4.svg
  public/assets/study/subject/study4_selected.svg
  public/assets/study/subject/study5.svg
  public/assets/study/subject/study5_selected.svg
  public/assets/study/subject/study6.svg
  public/assets/study/subject/study6_selected.svg
  public/assets/study/subject/study7.svg
  public/assets/study/subject/study7_selected.svg
  public/assets/study/subject/study8.svg
  public/assets/study/subject/study8_selected.svg
  public/assets/study/subject/study9.svg
  public/assets/study/subject/study9_selected.svg
  src/app/study/page.tsx
  src/components/.gitkeep
  src/components/common/Tabbar.tsx
  src/components/common/Tobbar.tsx
  src/components/study/Banner.tsx
  src/components/study/Tag.stories.tsx
  src/components/study/Tag.tsx
  src/components/study/review/ReviewContent.tsx
  src/components/study/review/ReviewTitle.tsx
  src/components/study/review/Reviews.tsx
  src/components/study/subject/SubjectContent.tsx
  src/components/study/subject/Subjects.tsx
  src/data/.gitkeep
  src/data/reviewData.ts
  src/data/subjectData.ts
  src/styles/theme.ts
Labels: 💄design

#18 [Feat] 홈 UI 추가 작업
  package.json
  public/assets/icons/ic_calendar.svg
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/app/home/page.tsx
  src/app/page.module.css
  src/app/signin/process4/page.tsx
  src/app/signin/terms/page.tsx
  src/components/common/Calendar.stories.tsx
  src/components/common/Calendar.tsx
  src/components/common/Card.stories.tsx
  src/components/common/Card.tsx
  src/components/common/Checkbox.stories.tsx
  src/components/common/Checkbox.tsx
  src/components/common/CustomInput.stories.tsx
  src/components/common/CustomInput.tsx
  src/components/common/ListBox.stories.tsx
  src/components/common/ListNumber.stories.tsx
  src/components/common/ListNumber.tsx
  src/components/common/Popup.stories.tsx
  src/components/common/Popup.tsx
  src/components/common/Toast.stories.tsx
  src/components/common/Toast.tsx
  src/components/home/AddTodoPopup.tsx
  src/components/home/Todo.tsx
  src/context/.gitkeep
  src/contexts/ToastContext.tsx
  src/data/Allergy.ts
  yarn.lock
Labels: 🛠feat, 🔧fix

#20 [Feat] 소식 UI - 학교, 교육청
  public/assets/icons/ic_eye.svg
  public/assets/images/news_bell.svg
  src/app/layout.tsx
  src/app/news/eduOffice/page.tsx
  src/app/news/layout.tsx
  src/app/news/school/page.tsx
  src/app/signin/completion/page.tsx
  src/components/common/ListBox.stories.tsx
  src/components/common/ListBox.tsx
  src/components/common/More.stories.tsx
  src/components/common/More.tsx
  src/components/common/Tabbar.tsx
  src/components/home/Meal.tsx
  src/components/home/MealTable.tsx
  src/components/home/MealTablePopup.tsx
  src/components/home/Notification.tsx
  src/components/home/Ready.tsx
  src/components/home/Todo.tsx
  src/components/news/HomeGuide.tsx
  src/components/news/Summary.tsx
  src/components/news/SummaryCard.tsx
  src/contexts/ToastContext.tsx
  src/data/newsData.ts
Labels: 🔧fix, 💄design

#21 [Feat] 회원가입 캘린더 및 팝업창 UI 마무리
  package.json
  src/app/signin/process2/page.tsx
  src/app/signin/process3-1/page.tsx
  src/components/common/Checkbox.stories.tsx
  src/components/common/Checkbox.tsx
  src/components/common/CustomInput.stories.tsx
  src/components/common/CustomInput.tsx
  src/components/common/Popup.tsx
  src/components/signin/SelectionPopup.tsx
  src/data/studentData.ts
  yarn.lock
Labels: 🛠feat, 💄design

#25 [Fix] ListBox 밀림 오류 해결
  src/components/common/Checkbox.tsx
Labels: 🔧fix

#28 [Feat] 소식 UI - 가정통신문 페이지
  public/assets/news/bell.svg
  public/assets/news/logo.svg
  public/assets/news/send.svg
  src/app/news/[summaryId]/page.tsx
  src/app/news/eduOffice/layout.tsx
  src/app/news/eduOffice/page.tsx
  src/app/news/school/layout.tsx
  src/app/news/school/page.tsx
  src/components/home/MealTable.tsx
  src/components/home/TimeTable.tsx
  src/components/news/HomeGuide.tsx
  src/components/news/Summary.tsx
  src/components/news/SummaryCard.stories.tsx
  src/components/news/SummaryCard.tsx
  src/data/newsData.ts
Labels: 💄design

#33 [Refactor] 공통 컴포넌트 리팩토링 및 수정사항
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Button.tsx
  src/components/common/Card.tsx
  src/components/common/Checkbox.tsx
  src/components/common/CustomInput.tsx
  src/components/common/ListBox.tsx
  src/components/common/Tabbar.tsx
  src/components/home/Todo.tsx
  src/components/news/HomeGuide.tsx
  src/components/school/home/HomeGuideRemind.tsx
  src/components/signin/SocialKakao.tsx
  src/data/commonData.ts
Labels: 💻refactor, 💄design

#35 [Feat] 학교생활 관련 UI
  public/assets/school/graduation.svg
  public/assets/school/teacher.svg
  src/app/school/notification/[id]/page.tsx
  src/app/school/notification/page.tsx
  src/app/school/parentReference/absentReason/page.tsx
  src/app/school/parentReference/workStudy/page.tsx
  src/components/common/ListBox.stories.tsx
  src/components/common/ListBox.tsx
  src/components/common/ListNumber.stories.tsx
  src/components/common/ListNumber.tsx
  src/components/common/More.tsx
  src/components/school/WhiteBox.tsx
  src/components/school/home/NotificationCheck.tsx
  src/components/school/home/ParentReference.tsx
  src/components/school/homeGuide/ReplyCompleted.tsx
  src/components/school/notification/LastNotifications.tsx
  src/components/school/notification/ListNumberBox.tsx
  src/components/school/notification/Notification.tsx
  src/components/school/notification/NotificationDetailList.tsx
  src/components/school/notification/TitleBox.tsx
  src/components/school/notification/TodayNotification.tsx
  src/components/school/notification/TopBox.tsx
  src/components/school/notification/TopContent.tsx
  src/components/school/parentReference/OptionList.tsx
  src/components/school/parentReference/Title.tsx
  src/data/notificationData.ts
Labels: 🛠feat, 💄design

#38 [Design] 마이페이지 UI - 홈, 프로필, 전자서명, 서류제출
  public/assets/icons/ic_checkbox_gray.svg
  public/assets/icons/ic_edit.svg
  src/app/mypage/children/layout.tsx
  src/app/mypage/document/layout.tsx
  src/app/mypage/document/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/layout.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/profile/signature/page.tsx
  src/components/common/Button.tsx
  src/components/common/Calendar.stories.tsx
  src/components/common/Checkbox.tsx
  src/components/common/CustomInput.stories.tsx
  src/components/common/CustomInput.tsx
  src/components/common/ListBox.tsx
  src/components/common/ListNumber.tsx
  src/components/common/Popup.tsx
  src/components/common/Topbar.tsx
  src/components/home/Notification.tsx
  src/components/mypage/DocsPopup.tsx
  src/data/mypageData.ts
Labels: 💄design

#41 [Design] 학교생활 관련 페이지
  public/assets/school/absent_form.svg
  public/assets/school/workstudy_form.svg
  src/app/school/page.tsx
  src/app/school/parentReference/absentReason/form/page.tsx
  src/app/school/parentReference/absentReason/submission/page.tsx
  src/app/school/parentReference/workStudy/form/page.tsx
  src/app/school/parentReference/workStudy/submission/page.tsx
  src/app/school/weeklyStudy/page.tsx
  src/app/signin/completion/page.tsx
  src/components/common/Button.stories.tsx
  src/components/common/Button.tsx
  src/components/common/Card.stories.tsx
  src/components/common/Card.tsx
  src/components/common/ListBox.tsx
  src/components/school/SchoolHomeTop.tsx
  src/components/school/home/DateSelect.tsx
  src/components/school/home/TimeTable.tsx
  src/components/school/home/TimeTable/SubjectBox.tsx
  src/components/school/home/TimeTable/TimeBox.tsx
  src/components/school/home/TimeTable/TimeTable.tsx
  src/components/school/home/TimeTable/TimeTableBox.tsx
  src/components/school/parentReference/SubmissionList.tsx
  src/components/school/weeklyStudy/DateSelect.stories.tsx
  src/components/school/weeklyStudy/DateSelect.tsx
  src/components/school/weeklyStudy/TodayStudyBox.tsx
  src/components/school/weeklyStudy/WeeklyNotification.tsx
  src/components/school/weeklyStudy/WeeklyStudyList.tsx
  src/components/signin/SelectionPopup.tsx
  src/data/submissionData.ts
  src/data/todayStudyData.ts
Labels: 🛠feat, 💄design

#42 [Design] 마이페이지 UI - 자녀 관리, 알림 UI
  public/assets/icons/ic_flip_gray.svg
  public/assets/icons/ic_noti.svg
  public/assets/images/grade1.svg
  public/assets/images/grade3.svg
  public/assets/images/grade6.svg
  public/assets/images/no_data.svg
  public/assets/images/rect_graphic.svg
  public/assets/images/round_graphic.svg
  public/assets/images/round_graphic_big.svg
  src/app/home/notification/page.tsx
  src/app/home/page.tsx
  src/app/mypage/children/page.tsx
  src/app/mypage/document/page.tsx
  src/app/mypage/page.tsx
  src/app/news/[summaryId]/page.tsx
  src/app/news/eduOffice/layout.tsx
  src/app/news/school/layout.tsx
  src/components/common/Calendar.stories.tsx
  src/components/common/Checkbox.stories.tsx
  src/components/common/Checkbox.tsx
  src/components/common/CustomInput.tsx
  src/components/common/Popup.stories.tsx
  src/components/common/Popup.tsx
  src/components/common/Tabbar.stories.tsx
  src/components/common/Tabbar.tsx
  src/components/common/Topbar.stories.tsx
  src/components/mypage/AllergyPopup.tsx
  src/components/mypage/ChangeChildPopup.tsx
  src/components/mypage/ChildProfile.tsx
  src/components/mypage/Keyword.tsx
  src/components/news/SummaryCard.stories.tsx
  src/components/notification/Filter.tsx
  src/components/notification/NotiCard.tsx
  src/data/commonData.ts
  src/data/mypageData.ts
  src/data/notifyData.ts
Labels: 🛠feat, 🔧fix, 💄design

#43 [Feat] 홈 - 시간표, 급식 API 연동
  src/apis/axios.ts
  src/components/common/Calendar.stories.tsx
  src/components/home/MealTable.tsx
  src/components/home/MealTablePopup.tsx
  src/components/home/TimeTable.tsx
Labels: 🛠feat

#45 [Fix] 카카오 소셜로그인 vercel 오류 해결
  src/app/auth/page.tsx
Labels: 🔧fix

#47 [Fix] 배포 오류
  src/app/mypage/children/page.tsx
  src/components/common/Calendar.stories.tsx
Labels: 🔧fix

#49 [Fix] Deploy 오류 - 페이지명 수정
  src/app/mypage/children/page.tsx
Labels: 🔧fix

#50 [Fix] Deploy 오류 - export 제거
  src/app/mypage/children/page.tsx
Labels: 🔧fix

#51 fix(#46): Deploy 오류 - Signbox export 제거
  src/app/mypage/profile/page.tsx
  src/app/mypage/profile/signature/page.tsx
Labels: 🔧fix

#52 [Docs] favicon 및 title 추가
  src/app/icon.png
  src/app/layout.tsx
Labels: 📝docs

#54 [Fix] Deploy 오류 - checkBox 오타 수정
  src/app/signin/process2/page.tsx
Labels: 🔧fix

#55 [Fix] Deploy 오류 - ListBox props 수정
  src/components/common/ListBox.tsx
Labels: 🔧fix

#56 [Fix] Deploy 오류 - window 객체 예외처리
  src/app/auth/page.tsx
Labels: 🔧fix

#57 [Fix] Deploy 오류 - window 오류 처리
  src/app/auth/page.tsx
Labels: 🔧fix

#63 [Fix] SSR 스타일링 풀리는 현상 해결
  src/app/layout.tsx
  src/components/common/NOSSR.tsx
Labels: 🔧fix

#71 [Feat] 키워드로 학교 검색 API 연동
  src/apis/school/getShcool.tsx
  src/app/signin/process3/page.tsx
  src/interface/School.ts
  src/redux/slices/userSlice.ts
Labels: 🛠feat

#76 [Fix] 배포 오류
  src/app/school/notification/[id]/page.tsx
Labels: 🔧fix

#73 [Feat] 이번주 시간표 API 연동
  src/apis/timetable/getWeekTimetable.tsx
  src/app/school/page.tsx
  src/components/school/home/TimeTable/TimeBox.tsx
  src/components/school/home/TimeTable/TimeTableBox.tsx
  src/interface/Timetable.ts
Labels: 🛠feat

#79 [Feat] 가정통신문 API 연동
  next.config.mjs
  src/app/news/[summaryId]/page.tsx
  src/app/news/eduOffice/[summaryId]/page.tsx
  src/app/news/eduOffice/layout.tsx
  src/app/news/eduOffice/page.tsx
  src/app/news/school/[summaryId]/page.tsx
  src/app/news/school/layout.tsx
  src/app/news/school/page.tsx
  src/components/home/AddTodoPopup.tsx
  src/components/home/Todo.tsx
  src/components/news/HomeGuide.tsx
  src/components/news/Summary.tsx
  src/components/news/SummaryCard.stories.tsx
  src/components/news/SummaryCard.tsx
Labels: 🛠feat

#85 [Feat] 마이페이지 API
  public/assets/icons/ic_alert.svg
  src/apis/axios.ts
  src/app/mypage/children/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/profile/signature/page.tsx
  src/app/news/eduOffice/[summaryId]/page.tsx
  src/app/news/eduOffice/page.tsx
  src/app/news/school/[summaryId]/page.tsx
  src/app/news/school/page.tsx
  src/app/signin/process4/page.tsx
  src/components/common/Calendar.tsx
  src/components/home/AddTodoPopup.tsx
  src/components/home/MealTable.tsx
  src/components/home/MealTablePopup.tsx
  src/components/home/Todo.tsx
  src/components/mypage/ChangeChildPopup.tsx
  src/components/mypage/ChildProfile.tsx
  src/components/mypage/Keyword.tsx
  src/components/news/HomeGuide.tsx
  src/components/news/SummaryCard.stories.tsx
  src/components/news/SummaryCard.tsx
  src/data/allergyData.ts
  src/hooks/auth/usePostKakaoToken.tsx
Labels: 🛠feat, 🔧fix

#88 [Fix] token 변경
  src/apis/axios.ts
  src/app/mypage/profile/signature/page.tsx
  src/app/signin/process3/page.tsx
  src/components/home/AddTodoPopup.tsx
  src/components/home/MealTable.tsx
  src/components/home/Notification.tsx
  src/components/home/TimeTable.tsx
  src/components/school/notification/LastNotifications.tsx
  src/components/school/notification/TitleBox.tsx
  src/components/school/notification/TodayNotification.tsx
Labels: 🔧fix

#90 [Docs] 더미데이터 추가
  src/app/mypage/document/page.tsx
  src/app/news/eduOffice/page.tsx
  src/app/news/school/page.tsx
  src/components/common/ListBox.tsx
  src/components/school/SchoolHomeTop.tsx
  src/components/school/home/HomeGuideRemind.tsx
  src/components/school/home/TimeTable/TimeTableBox.tsx
  src/components/school/weeklyStudy/WeeklyNotification.tsx
  src/components/study/review/ReviewTitle.tsx
  src/data/mypageData.ts
  src/data/newsData.ts
  src/data/notifyData.ts
  src/data/todayStudyData.ts
Labels: 📝docs

#92 [Fix] 배포 및 토큰 이상 오류
  src/apis/axios.ts
  src/app/mypage/profile/page.tsx
  src/app/mypage/profile/signature/page.tsx
Labels: 🔧fix

#94 [Fix] 로그인 에러 해결
  src/apis/auth/postKakaoToken.tsx
  src/apis/axios.ts
  src/apis/school/getShcool.tsx
  src/apis/user/postUser.tsx
  src/app/auth/page.tsx
  src/app/signin/process4/page.tsx
Labels: 🔧fix

#97 [Fix] localStorage 오류 수정
  src/apis/axios.ts
  src/app/signin/process4/page.tsx
Labels: 🔧fix

#98 [Fix] 2차 QA 반영
  public/assets/school/workstudy_form.svg
  src/app/mypage/page.tsx
  src/components/common/ListBox.tsx
  src/components/common/ListNumber.tsx
  src/components/home/Ready.tsx
  src/components/notification/NotiCard.tsx
  src/components/school/SchoolHomeTop.tsx
  src/components/school/homeGuide/ReplyCompleted.tsx
  src/components/school/notification/Notification.tsx
  src/components/school/notification/TitleBox.tsx
  src/components/school/notification/TodayNotification.tsx
  src/components/school/weeklyStudy/TodayStudyBox.tsx
  src/components/school/weeklyStudy/WeeklyStudyList.tsx
  src/data/notifyData.ts
  src/data/reviewData.ts
  src/data/todayStudyData.ts
Labels: 🛠feat, 🔧fix

#99 [Fix] 교육청 상세 보기 수정
  src/app/news/eduOffice/page.tsx
  src/app/news/school/page.tsx
  src/components/news/Summary.tsx
  src/components/news/SummaryCard.tsx
Labels: 🔧fix

#105 [Feat] 캘린더 API 연동 반영
  src/components/school/home/TimeTable/SubjectBox.tsx
  src/components/school/home/TimeTable/TimeBox.tsx
  src/components/school/home/TimeTable/TimeTableBox.tsx
  src/interface/Timetable.ts
Labels: 🛠feat, 💄design

#106 [Fix] 급식표 날짜 오류 및 서명 localStorage 오류 수정
  src/app/mypage/profile/page.tsx
  src/app/mypage/profile/signature/page.tsx
  src/app/news/eduOffice/page.tsx
  src/app/news/school/page.tsx
  src/app/school/notification/page.tsx
  src/components/common/ListBox.tsx
  src/components/common/ListNumber.tsx
  src/components/home/MealTablePopup.tsx
  src/components/news/SummaryCard.tsx
Labels: 🔧fix, 💄design

#108 [Fix] Styled Components 오류 해결
  next.config.mjs
  src/app/layout.tsx
  src/app/registry.tsx
  src/components/common/NOSSR.tsx
  src/stories/Configure.mdx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/styles/GlobalStyles.ts
Labels: 🔧fix, 🤝🏻style
